name: Shabby Pages daily build

on:
  push:
    branches: [dev]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # clone this repo to $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest tag
        id: tag
        run: |
          echo "::set-output name={TAG}::{git tag | sort -n | tail -1}"

      # run the daily-build script
      - name: Generate the images
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          python3 -m pip install -U pip virtualenv
          python3 -m virtualenv --python="$(command -v python3)" .venv
          source .venv/bin/activate
          python3 -m pip install git+https://github.com/sparkfish/augraphy
          python3 -m pip install -r requirements.txt
          python3 daily_build.py

      # release the daily build
      - name: Daily Shabby Pages Sample
        uses: softprops/action-gh-release@v1
        with:
          files: cropped/shabby/*
          tag_name: ${{steps.tag.outputs.TAG}}
